### ISSUE TITLE
Add <vector> to files

### ISSUE THREAD

**Issue by msoeken** [hriener/lorina#13]
The files `lorina/aiger.hpp` and `lorina/detail/utils.hpp` are using `std::vector` without including it which can lead to problems, see, e.g., here:

https://travis-ci.org/lsils/mockturtle/jobs/523896213#L1586

**Comment by hriener** [comment]
Thanks. Fixed in commit 8bb02eac2cbf002aad5b3b05bdd09fafa7525af2
