### ISSUE TITLE
operator== on truth tables?

### ISSUE THREAD

**Issue by mfernan2** [hriener/lorina#29]
`static_truth_table` and `dynamic_truth_table` do not implement `operator==` and `operator!=`, so code like `tt1 == tt2` does not work. It seems you still can compare truth tables with something like the following (untested) code:

```cpp
bool eq = true;
for (auto it = tt1.begin(), it2 = tt2.begin(); ; ++it, ++it2) {
  if (it == tt1.end()) {
    eq &= it2 == tt2.end();
    break;
  } else if (it2 == tt2.end()) {
    eq = false;
    break;
  }
  eq &= *it == *it2;
}
```

Is it possible to implement `operator==` and `operator!=` on these classes to avoid having to do this? It should be possible to do some template-based specialization to optimize these too.

OTOH perhaps I've misunderstood something and equality comparison makes no sense on these classes. In which case, I would be interested to learn of this too.

**Comment by msoeken** [comment]
This issue may be reported in the wrong GitHub project (truth tables are implemented in [msoeken/kitty](https://github.com/msoeken/kitty)). These operators are implemented in the `operators.hpp` header:

https://libkitty.readthedocs.io/en/latest/reference.html#_CPPv4N5kittyeqERK19dynamic_truth_tableRK19dynamic_truth_table

**Comment by hriener** [comment]
I agree. Thanks for the answer.

**Comment by mfernan2** [comment]
Sorry, yes, you're correct. I'll file a new issue on Kitty.
