### ISSUE TITLE
Integration with the conan package manager

### ISSUE THREAD

**Issue by ruanformigoni** [hriener/lorina#31]
This issue is a reference to the pull request #30. Where a implemented feature integration with [conan](https://conan.io/) was presented.

I use the EPFL logic sythesis libraries quite frequently, if the feature is approved I can implement it to the other libraries as well.

Best.

**Comment by hriener** [comment]
Currently, none of the core developers uses `conan`. Consequently, we would not be able to maintain this feature in the future, or even recognize if it breaks or changes are required.

Is it possible to keep the `conan` files external in another project? We can accept the changes to the CMake files and link to the external project form the main project page.

**Comment by ruanformigoni** [comment]
It is possible, but it would be harder to maintain. If you'd like I could maintain the conan code, only performing changes throught approved pull requests.

**Comment by hriener** [comment]
I appreciate having `conan` support in an external repository maintained by you.

**Comment by hriener** [comment]
Seems to be resolved.

We can re-open it, in case there is any progress.
