### ISSUE TITLE
Compile error in clang 6.0.0

### ISSUE THREAD

**Issue by msoeken** [hriener/lorina#4]
I got a compile error in C++17 mode with LLVM 6.0.0. The call to `apply` is ambiguous because there is a method in `std` applicable as well due to argument-dependent lookup.

In order to fix the issue, it is sufficient to replace `apply` in the following line by `detail::apply`. 

https://github.com/hriener/lorina/blob/ac900718cec575c63ed344eddee9a2f58bb8c284/include/lorina/detail/utils.hpp#L120

**Comment by hriener** [comment]
Thank you for pointing this out.

I integrated `gcc-7` and `clang-6` into the travis CI script to test C++17 compatibility. Surprisingly `clang-6` does not fail, but `gcc-7` does.

Anyways, I tried to fix the issue in commit 04baeda35d5456b73dc7d1076fb0c423d4a9263c.

Could you verify if the commit solves the problem?

**Comment by hriener** [comment]
Seems to be resolved.

I close this issue.
